CRM_project/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#index"

  resources :homes
  resources :technicians do
    resources :jobs
  end

  resources :customers do
    resources :jobs
  end

end

CRM_project/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :jobs

  accepts_nested_attributes_for :jobs
end

CRM_project/app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :customer
  belongs_to :technician
end

CRM_project/app/models/technician.rb
class Technician < ActiveRecord::Base
  has_many :jobs
  has_many :customers, through: :jobs

  accepts_nested_attributes_for :jobs
  accepts_nested_attributes_for :customers
end
end

CRM_project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

CRM_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

CRM_project/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers=Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer=Customer.create(customer_params)

    redirect_to customers_path
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)

    redirect_to edit_customer_path(@customer)
  end

  def edit
    @customer=Customer.find(params[:id])

  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :phone_num, :phone_num2, :address,
                                      jobs_attributes: [:technician, :brand, :model_num, :serial_num, :purchase_date, :scheduled_date,
                                                                  :description, :created_at, :updated_at, :description, :note, :warranty, :status,
                                                                  :performed])
  end

end

CRM_project/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @jobs=Job.where.not(jobs: {scheduled_date: nil}).references(:jobs)
  end

  def new
    @customer=Customer.new
    @customer.jobs.build
  end

  def create
    @customer=Customer.create(customer_params)
    @customer.jobs.create(jobs_params)

    redirect_to customers_path
  end


  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :phone_num, :phone_num2, :address)
  end

  private
  def jobs_params
    params.require(:job).permit(:technician, :brand, :model_num, :serial_num, :purchase_date, :scheduled_date,
                                :description, :created_at, :updated_at, :description, :note, :warranty, :status,
                                :performed)
  end

end

CRM_project/app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @customer=Customer.find(params[:customer_id])
    @jobs=@customer.jobs.all
  end

  def new
    @customer=Customer.find(params[:customer_id])
    @job=Job.new
  end

  def create
    @customer=Customer.find(params[:customer_id])
    @job = @customer.jobs.create(jobs_params)

    redirect_to customer_job_path(@customer, @job)
  end

  def show
    @customer=Customer.find(params[:customer_id])
    @job=@customer.jobs.find(params[:id])
  end

  def edit
    @job=Job.find(params[:id])
    @customer=Customer.find(params[:customer_id])
  end

  def update
    @customer=Customer.find(params[:customer_id])
    @job=Job.find(params[:id])
    @job.update(jobs_params)

    redirect_to edit_customer_job_path(@customer, @job)
  end

  private
  def jobs_params
    params.require(:job).permit(:technician, :brand, :model_num, :serial_num, :purchase_date, :scheduled_date,
                                :description, :created_at, :updated_at, :description, :note, :warranty, :status,
                                :performed)
  end
end

CRM_project/app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController

  def index
    @technicians=Technician.all
  end

  def new
    @technician=Technician.new
  end

  def create
    @technician=Technician.create(technician_params)

    redirect_to technician_path(@technician)
  end

  def show
    @technician=Technician.find(params[:id])
  end

  def edit

  end

  def update
    @technician = Technician.find(params[:id])
    @technician.update(technician_params)

    redirect_to edit_technician_path(@technician)
  end

  private
   def technician_params
    params.require(:technician).permit(:name)

  end
end

CRM_project/app/helpers/application_helper.rb
module ApplicationHelper
end

CRM_project/app/views/customers/_form.html.erb
<div class="col-xs-6" "col-md-4">
<%= form_for @customer do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_num, class: "form-control" %>

  <%= f.label :second_phone_number%>
  <%= f.text_field :phone_num2, class: "form-control" %>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.submit %>
<%end%>
</div>

CRM_project/app/views/customers/edit.html.erb
<h1> The customer <%= "#{@customer.first_name} #{@customer.last_name}"%> has been updated </h1>

<%= link_to "Go Back", customers_path %>

CRM_project/app/views/customers/index.html.erb
<% @customers.each do |customer| %>
<ul>
  <li><%= link_to "#{customer.first_name} #{customer.last_name}", customer_path(customer) %></li>
</ul>
<% end %>

<%= link_to "Create Customer", new_customer_path %>

CRM_project/app/views/customers/show.html.erb
<%= render 'form' %>

<%=link_to "create a job", new_customer_job_path(@customer) %>

CRM_project/app/views/homes/_form.html.erb
<div class="col-xs-6" "col-md-4">
  <%= form_for @customer do |f| %>

  <h3>Customer</h3>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_num, class: "form-control" %>

  <%= f.label :second_phone_number%>
  <%= f.text_field :phone_num2, class: "form-control" %>

  <%= f.label :address %>
  <%= f.text_field :address, class: "form-control" %>



  <h3>Job contents</h3>
  <%= f.fields_for :jobs do |field| %>
  <%= field.label :brand%>
  <%= field.text_field :brand, class: "form-control" %>

  <%= field.label :model_num %>
  <%= field.text_field :model_num, class: "form-control" %>

  <%= field.label :serial_num %>
  <%= field.text_field :serial_num, class: "form-control" %>

  <%= field.label :purchase_date %>
  <%= field.date_select :purchase_date, class: "form-control" %>

  <%= field.label :scheduled_date %>
  <%= field.date_select :scheduled_date, class: "form-control" %>
  <% end %>

  <%= f.submit %>
  <%end%>
</div>

CRM_project/app/views/homes/index.html.erb
<div class="row">
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-tasks fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @jobs.length %></div>
            <div>New Jobs!</div>
          </div>
        </div>
      </div>
      <%=link_to raw('        <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>'),  customers_path %>

    </div>
  </div>
  
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-tasks fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">12</div>
            <div>Scheduled Jobs!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-shopping-cart fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">124</div>
            <div>Parts Orders!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-support fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge">13</div>
            <div>Issues!</div>
          </div>
        </div>
      </div>
      <a href="#">
        <div class="panel-footer">
          <span class="pull-left">View Details</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
    </div>
  </div>
</div>

CRM_project/app/views/homes/new.html.erb
<%= render 'form' %>

CRM_project/app/views/jobs/_form.html.erb
<div class="col-xs-6" "col-md-4">
  <h3>Customer</h3>
  <%= link_to "#{@customer.first_name} #{@customer.last_name}", customer_path(@customer, @job) %>
  <%= form_for [@customer, @job] do |f| %>
  <%= f.label :brand%>
  <%= f.text_field :brand, class: "form-control" %>

  <%= f.label :model_num %>
  <%= f.text_field :model_num, class: "form-control" %>

  <%= f.label :serial_num %>
  <%= f.text_field :serial_num, class: "form-control" %>

  <%= f.label :purchase_date %>
  <%= f.date_select :purchase_date, class: "form-control" %>

  <%= f.label :scheduled_date %>
  <%= f.date_select :scheduled_date, class: "form-control" %>

  <%= f.submit %>
  <%end%>
</div>

CRM_project/app/views/jobs/edit.html.erb
<h1> The Job <%= @job.id %> has been updated </h1>

<%= link_to "Go Back", customer_jobs_path(@customer) %>

CRM_project/app/views/jobs/index.html.erb
<% @jobs.each do |job| %>
<%=link_to job.id, customer_job_path(@customer, job) %>
<% end %>

CRM_project/app/views/jobs/show.html.erb
<%= render 'form' %>

CRM_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRMProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-brand"  <%= link_to "Wonsik Jeong", root_path %> </a>
    </div>
    <% if current_user %>
      <%= link_to raw('<i class="glyphicon glyphicon-log-out"></i> Signout'), destroy_user_session_path, :method => :delete, class: "btn btn-default btn-lg"  %>
    <% else %>
        <%= link_to raw('<i class="glyphicon glyphicon-thumbs-up"></i> Signup'), new_user_registration_path, class: "btn btn-default btn-lg" %>

        <%= link_to raw('<i class="glyphicon glyphicon-log-in"></i> Login'), new_user_session_path, class: "btn btn-default btn-lg" %>

    <% end %>
    <%= link_to "New Job", new_home_path %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
  </html>

CRM_project/app/views/technicians/_form.html.erb
<%= form_for [@technician] do |f| %>
<div class="col-lg-6">
  <div class ="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control"  %>

    <%= f.submit %>
    <%end%>
  </div>
</div>

CRM_project/app/views/technicians/edit.html.erb
<h1>Page has been editted</h1>

<%= link_to "Go Back", technicians_path %>

CRM_project/app/views/technicians/index.html.erb
<% @technicians.each do |technician| %>
<ul>
  <li><%=link_to technician.name, technician_path(technician) %></li>
</ul>
<%end %>


<%= link_to "New Technician", new_technician_path %>